name: Cleanup attendance data

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Remove data directory
        run: |
          rm -rf data
          mkdir -p data
      - name: Commit cleanup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "[bot] semester cleanup: reset data/ directory" || echo "Nothing to commit"
          git push

